//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDiplom.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionTypeRole
    {
        public int Id { get; set; }
        public int RightId { get; set; }
        public int ActionTypeId { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual Right Right { get; set; }
        public virtual Role Role { get; set; }
    }
}
