//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDiplom.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public int UserId { get; set; }
        public int ActionTypeId { get; set; }
        public System.DateTime DateAction { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual Document Document { get; set; }
        public virtual User User { get; set; }
    }
}
